<?php
// Heading
$_['heading_title']					 = 'iPayy - Carrier based payment';
$_['ipayy_logo_url']				 = 'https://portal.ipayy.com/v001/images/logo.png';
// Text
$_['text_payment']					 = 'Payment';
$_['text_success']					 = 'Success: You have modified iPayy settings!';
$_['text_ipayy']				 	 = '<a onclick="window.open(\'https://www.ipayy.com\');"><img src="' . $_['ipayy_logo_url'] . '" alt="iPayy" title="iPayy" height="30" /></a>';
$_['text_authorization']			 = 'Authorization';
$_['text_sale']						 = 'Sale';

// Entry
$_['entry_merchant_id']				= 'Merchant Id:';
$_['entry_merchant_help']				= 'Merchant Id generated by <a href="https://portal.ipayy.com">https://portal.ipayy.com</a>';
$_['entry_application_id']			= 'Application Id:';
$_['entry_application_help']			= 'Login to your merchant account at <a href="https://portal.ipayy.com">https://portal.ipayy.com</a> to get your application id';
$_['entry_item_display']			= 'Display Item Name as:';
$_['entry_item_help']			= 'What should be displayed to customer as item name when the customer goes to payment page.';
$_['entry_item_options']			= array("Store Name", "Item Name", "Subdomain Name", "Domain Name", "Custom");
$_['entry_debug']					 = 'Debug Mode:<br/><span class="help">Logs additional information to the system log.</span>';
$_['entry_total']                    = 'Max Total:<br /><span class="help">The checkout total the order must not be more than specified amount.</span>';
$_['entry_completed_status']         = 'Completed Status:';
$_['entry_denied_status']			 = 'Denied Status:';
$_['entry_failed_status']			 = 'Failed Status:';
$_['entry_status']					 = 'Status:';
$_['entry_sort_order']				 = 'Sort Order:';

//Defaults
$_['default_max_total']				= 500;
$_['default_sort_order']				= 0;
$_['default_item_display']			= $_['entry_item_options'][0];

// Error
$_['error_permission']				 = 'Warning: You do not have permission to modify payment iPayy!';
$_['error_merchant_id_required']					 = 'Merchant Id is required!';
$_['error_application_id_required']					 = 'Application Id is required!';
$_['error_item_display_other_required']					 = 'Please fill in the box!';
?>